# 通用配置
name : 'web-api'         # 服务名称
port : 10051             # 服务端口
host : 192.168.10.33     # 服务IP地址
debug : 'true'                 # 服务debug模式

# JWT配置
jwt:
  key: 'zIcG6foVHFSHNtOf' # JWT签发密钥

# Redis配置
redis:
  host: '127.0.0.1'       # redis IP地址
  port: 3306              # redis 端口
  expire: 120             # 个别key 过期时间