# Copyright 2023 The Mini Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# 通用配置
name : web-api                              # 服务名称
host : 192.168.10.33                        # 服务IP地址
port : 10052                                # 服务端口
runmode: debug                              # Gin 开发模式, 可选值有：debug, release, test

# 日志配置
log:
  disable-caller: false                     # 是否开启 caller，如果开启会在日志中显示调用日志所在的文件和行号
  disable-stacktrace: false                 # 是否禁止在 panic 及以上级别打印堆栈信息
  level: debug                              # 指定日志级别，可选值：debug, info, warn, error, dpanic, panic, fatal
  format: console                           # 指定日志显示格式，可选值：console, json
  output-paths: [/tmp/miniblog.log, stdout] # 指定日志输出位置

db:
  host: 10.211.55.3                         # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  username: root                            # MySQL 用户名(建议授权最小权限集)
  password: g8azxYLFm2                      # MySQL 用户密码
  database: mini                            # mini 系统所用的数据库名
  max-idle-connections: 100                 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100                 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s             # 空闲连接最大存活时间，默认 10s
  log-level: 4                              # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# JWT配置
jwt:
  key: zIcG6foVHFSHNtOf                     # JWT签发密钥

# Redis配置
redis:
  host: 127.0.0.1                           # redis IP地址
  port: 3306                                # redis 端口
  expire: 120                               # 个别key 过期时间