---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3.5.0
      - name: Run a one-line script
        run: echo Hello
name: Mini CI
'on':
  pull_request:
    branches:
      - $default-branch
  push:
    branches:
      - $default-branch