---
jobs:
  goreleaser:
    name: workflows at release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 1.20
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
name: Go releaser
'on':
  push:
    tags:
      - '*'
permissions:
  contents: write